"""initial_schema

Revision ID: 414d0978b9fb
Revises: 
Create Date: 2026-03-27 23:52:29.329149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db_types import GeographyOrText


# revision identifiers, used by Alembic.
revision: str = '414d0978b9fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('service_zone', GeographyOrText(geometry_type='POLYGON', srid=4326), nullable=True),
    sa.Column('operating_hours', sa.JSON(), nullable=True),
    sa.Column('max_pickup_radius_meters', sa.Integer(), nullable=True),
    sa.Column('max_detour_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_domain'), ['domain'], unique=True)

    op.create_table('analytics_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('RIDE_REQUESTED', 'RIDE_MATCHED', 'RIDE_STARTED', 'RIDE_COMPLETED', 'RIDE_CANCELLED', 'VAN_ONLINE', 'VAN_OFFLINE', 'DEMAND_SURGE', name='event_type'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('location', GeographyOrText(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_event_type'), ['event_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('EMPLOYEE', 'DRIVER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='user_status'), nullable=True),
    sa.Column('home_location', GeographyOrText(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('home_address', sa.String(), nullable=True),
    sa.Column('default_destination', GeographyOrText(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('default_destination_address', sa.String(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('PUSH', 'SMS', 'EMAIL', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status'), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_user_read_at', ['user_id', 'read_at'], unique=False)

    op.create_table('ride_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('pickup_location', GeographyOrText(geometry_type='POINT', srid=4326), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('destination', GeographyOrText(geometry_type='POINT', srid=4326), nullable=False),
    sa.Column('destination_address', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'MATCHING', 'MATCHED', 'DRIVER_EN_ROUTE', 'ARRIVED_AT_PICKUP', 'PICKED_UP', 'IN_TRANSIT', 'ARRIVED_AT_DESTINATION', 'DROPPED_OFF', 'COMPLETED', 'CANCELLED_BY_EMPLOYEE', 'CANCELLED_BY_ADMIN', 'NO_SHOW', 'REASSIGNED', 'FAILED_NO_CAPACITY', 'FAILED_DRIVER_UNREACHABLE', 'FAILED_OPERATIONAL_ISSUE', 'SCHEDULED_REQUESTED', 'SCHEDULED_QUEUED', 'MATCHING_AT_DISPATCH_WINDOW', name='ride_request_status'), nullable=True),
    sa.Column('scheduled_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_pickup_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('actual_dropoff_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ride_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ride_requests_status'), ['status'], unique=False)

    op.create_table('vans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=True),
    sa.Column('current_location', GeographyOrText(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'OFFLINE', 'MAINTENANCE', name='van_status'), nullable=True),
    sa.Column('last_location_update', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('current_occupancy >= 0 AND current_occupancy <= capacity', name='check_occupancy'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vans_license_plate'), ['license_plate'], unique=True)
        batch_op.create_index(batch_op.f('ix_vans_status'), ['status'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('van_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'DISPATCH_READY', 'ACTIVE_TO_PICKUP', 'ACTIVE_IN_TRANSIT', 'ACTIVE_MIXED', 'COMPLETED', 'REASSIGNED', 'CANCELLED', 'FAILED_OPERATIONAL_ISSUE', name='trip_status'), nullable=True),
    sa.Column('route', sa.JSON(), nullable=False),
    sa.Column('total_distance_meters', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['van_id'], ['vans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index('idx_trips_accepted_at', ['accepted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_status'), ['status'], unique=False)

    op.create_table('dispatch_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('ride_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('from_state', sa.String(length=100), nullable=True),
    sa.Column('to_state', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_events_actor_type'), ['actor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_events_event_type'), ['event_type'], unique=False)

    op.create_table('trip_passengers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('ride_request_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('pickup_stop_index', sa.Integer(), nullable=False),
    sa.Column('dropoff_stop_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'NOTIFIED', 'PICKED_UP', 'DROPPED_OFF', 'NO_SHOW', name='passenger_status'), nullable=True),
    sa.Column('pickup_eta', sa.TIMESTAMP(), nullable=True),
    sa.Column('actual_pickup_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('actual_dropoff_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('pickup_stop_index < dropoff_stop_index', name='check_stop_order'),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_passengers')
    with op.batch_alter_table('dispatch_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_dispatch_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_dispatch_events_actor_type'))

    op.drop_table('dispatch_events')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index('idx_trips_accepted_at')
        batch_op.drop_index(batch_op.f('ix_trips_status'))

    op.drop_table('trips')
    with op.batch_alter_table('vans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vans_status'))
        batch_op.drop_index(batch_op.f('ix_vans_license_plate'))

    op.drop_table('vans')
    with op.batch_alter_table('ride_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ride_requests_status'))

    op.drop_table('ride_requests')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_user_read_at')

    op.drop_table('notifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_event_type'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_domain'))

    op.drop_table('companies')
    # ### end Alembic commands ###
